### ISSUE TITLE
Bootcamp Opt-out

### ISSUE THREAD

**Issue by amritasahu47** [pmelchior/usrp-sciprog#132]
https://github.com/amritasahu47/USRP

Not sure if I did everything right, but here's my best attempt! I'm not very familiar with git, so even if I did happen to complete the challenge correctly I'd like to opt-in to various parts of the bootcamp.

**Comment by pmelchior** [comment]
Hi Amrita, thanks for filling out the challenge. Your solution looks good. I also suggest that you still attend bootcamp because it covers many aspects you may not have heard of (including git).
