### ISSUE TITLE
Bootcamp Opt-Out

### ISSUE THREAD

**Issue by orbinose** [pmelchior/usrp-sciprog#136]
https://github.com/orbinose/usrp2024.git

**Comment by pmelchior** [comment]
I can't find your repo. Please correct the link

**Comment by orbinose** [comment]
https://github.com/orbinose/usrp2024

**Comment by pmelchior** [comment]
OK, close but not quite. See my comment here: https://github.com/pmelchior/usrp-sciprog/issues/138#issuecomment-2150012752

**Comment by orbinose** [comment]
Fixed!

**Comment by pmelchior** [comment]
Well done
