### ISSUE TITLE
Bootcamp Opt-out

### ISSUE THREAD

**Issue by TejahniDesire** [pmelchior/usrp-sciprog#137]
https://github.com/TejahniDesire/USRP_OPT_OUT.git

**Comment by pmelchior** [comment]
That's fine. There's one minor mistake, though. The weights for this problem need to be inverse _variance_, not inverse _standard deviation_, so they need to be squared. However, I just saw that the numpy docs for the method specify this incorrectly as well. But otherwise fine.
