### ISSUE TITLE
Bootcamp Opt-Out

### ISSUE THREAD

**Issue by sfiler** [pmelchior/usrp-sciprog#138]
Shannon Filer Opt Out. File name is [USRP24 Opt Out (2).ipynb](https://github.com/sfiler/usrptesting/blob/master/USRP24%20Opt%20Out%20(2).ipynb)

**https://github.com/sfiler/usrptesting.git**

**Comment by pmelchior** [comment]
That's close, but not quite it. Your solution for the best-fit coefficients with `polyfit` does not consider the different errors on y. It's therefore not the maximum-likelihood solution. However, the method can be provided with weights. If you provide inverse variance weights, it becomes the maximum-likelihood solution. (Note that their docs incorrectly state that you can use `w=1/std_y`, but inverse _variance_ is the square of that.)

**Comment by sfiler** [comment]
Thank you for the correction! I've updated the code with the MLE least squares solution, with inverse variance weights. Let me know if there's anything else I can do better! This one is labeled USRP Opt-Out (3). 

https://github.com/sfiler/usrptesting.git

**Comment by pmelchior** [comment]
That's good.
