### ISSUE TITLE
2018 logistics

### ISSUE THREAD

**Issue by adrn** [pmelchior/usrp-sciprog#59]
# Before attending

### Windows:
* Install Linux (Ubuntu) https://docs.microsoft.com/en-us/windows/wsl/install-win10

### Mac:
* Make sure command line tools installed
* Make sure git works

### Linux:
* ??

### All:
* Install Anaconda with Python 3!

### TODO:
* Write / check a script to make sure Python 3 installed, Python packages, git, ssh
* If possible, everyone should start looking at http://nbviewer.jupyter.org/github/jakevdp/WhirlwindTourOfPython/blob/master/Index.ipynb
* Code of conduct

**Comment by agoulding** [comment]
Installing Linux on Tuesday:
https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by adrn** [comment]
# Seminars

1. June 19 - How to find and read papers (Adrian)
2. June 26 - Stats (Mat)
3. July 3 - Be a good scientist (??? + all)
4. July 10 - Visualization (Peter)
5. July 17 - How to write a paper / Latex (???)
6. July 31 - How to give presentations (Andy)
7. Aug 6 - Practice talks (??? + all)
