### ISSUE TITLE
Bootcamp Opt-Out

### ISSUE THREAD

**Issue by mdodici** [pmelchior/usrp-sciprog#96]
[Here](https://github.com/mdodici/USRP21-OptOut-Dodici/tree/master) is my opt-out program. I would perhaps like to attend some of the sessions for a refresher on certain topics once we know the full schedule, if that's alright. Thanks!

**Comment by pmelchior** [comment]
Hi Mark, I can't open the link. It seems that you haven't pushed to repo to github (yet).

**Comment by mdodici** [comment]
Hi Peter, I think it was because I had the repo set to private. Does it work now?

**Comment by pmelchior** [comment]
Yes, works. Also, solution accepted. You can start working with your mentor directly on June 7.
