### ISSUE TITLE
Bootcamp Opt-out

### ISSUE THREAD

**Issue by sejones22** [pmelchior/usrp-sciprog#98]
https://github.com/sejones22/usrp2021

I would be glad to mentor and help any way possible! The bootcamp will be a nice refresher for myself too. I think my only conflict would be a few science meetings on Friday. Thank you!

**Comment by pmelchior** [comment]
Hi Sinclaire, your solution is accepted. Your help with the bootcamp the bootcamp is very much appreciated. Sophie, Chang-Goo, and Ben can provide details, but just monitoring #usrp2021 for questions would help.
